# Generated by Django 5.1.6 on 2025-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=120)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
